name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['main']

jobs:
  lint:
    name: Lint (Ruff)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Ruff (lint)
        uses: astral-sh/ruff-action@v1
        with:
          args: "check ."

  security:
    name: Dependências (pip-audit)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Instala dependências
        run: pip install -r requirements.txt
      - name: pip-audit (SCA)
        uses: pypa/gh-action-pip-audit@v1.1.0
        continue-on-error: true

  tests:
    name: Testes (pytest)
    runs-on: ubuntu-latest
    needs: [lint, security]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run pytest (JUnit + Coverage)
        env:
          PYTHONPATH: ${{ github.workspace }}/src   # <— aqui está o truque
        run: |
          mkdir -p reports
          pytest -q \
            --junitxml=reports/junit.xml \
            --cov=src \
            --cov-report=xml:reports/coverage.xml \
            --cov-report=html:reports/html

      - name: Upload JUnit
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports/junit.xml

      - name: Upload Coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: reports/html

