name: CI
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['main']

jobs:
  lint:
    name: Lint (Ruff)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      # Ruff como Action oficial (Marketplace)
      - name: Ruff (lint)
        uses: astral-sh/ruff-action@v1
        with:
          args: "check ."

  security:
    name: Dependências (pip-audit)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Instala dependências
        run: pip install -r requirements.txt
      # pip-audit como Action oficial (Marketplace)
      - name: pip-audit (SCA)
        uses: pypa/gh-action-pip-audit@v1
        # deixe true se quiser ga
